server:
  port: 8080

spring:
  application:
    name: oracle-mcp-server
  ai:
    mcp:
      server:
        name: oracle-mcp-server
        version: 1.0.0
        type: ASYNC

logging:
  config: classpath:logback-spring.xml

oracle:
  connection:
    url: jdbc:oracle:thin:@{ip}:{port}:{database}
    username: {username}
    password: {password}
